---


# - hosts: all
#   become: yes
#   become_user: root
#   user: ubuntu
#   vars:
#     pip_install_packages:
#       - name: docker
#   roles:
#     - geerlingguy.docker
#     - geerlingguy.pip

- hosts: tag_redis
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: Update repositories cache and install "redis" package
      apt:
        name: redis
        update_cache: yes
    - name: Start service redis, if not started
      service:
        name: redis
        state: started
    # - name: Stop service redis
    #   service:
    #     name: redis
    #     state: stopped

